# Generated by Django 5.1.4 on 2026-04-26 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employee_fcm_token_user_fcm_token'),
        ('tasks', '0002_remove_maintask_attachments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subtasks', to='accounts.employee'),
        ),
    ]
