# Generated by Django 5.1.4 on 2026-03-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employee_created_at_alter_employee_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('it', 'IT'), ('department_head', 'Department Head')], max_length=50, unique=True),
        ),
    ]
