# Generated by Django 5.1.4 on 2026-04-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging token for mobile/web notifications.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging token for web notifications.', max_length=500, null=True),
        ),
    ]
